accounts/urls.py
from django.urls import path, include
from django.contrib.auth import urls as auth_urls

from . import views

app_name = "accounts"
urlpatterns = [
    path("", include(auth_urls)),
    path("register/", views.register, name="register"),
]

blogmaker_lite/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),    
    path("", include("blogs.urls")),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = "blogs"

urlpatterns = [
    path("blogs/", views.blogs, name="blogs"),
    path("meus_blogs/", views.meus_blogs, name="meus_blogs"),
    path("blogs/<int:blog_id>/", views.blog, name="blog"),
    path("posts/<int:post_id>/", views.post, name="post"),
    path("new_blog/", views.new_blog, name="new_blog"),
    path("new_post/<int:blog_id>/", views.new_post, name="new_post"),    
    path("", views.index, name="index"),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE) ## adicionado para controlar o 'dono' do Blog    

    def __str__(self):
        return self.title
    
class BlogPost(models.Model):
    title = models.CharField(max_length=500)
    body = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title[:50]

blogs/forms.py
from django import forms

from .models import Blog, BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ["title", "description"]
        labels = {"title": "Título",
                  "description":"Descrição",}
        
class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ["title", "body"]

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        print("POST DATA: ", request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("blogs:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

blogs/views.py
from django.shortcuts import render, redirect
from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, "blogs/index.html")

# a view function defines what data the user can view on the corresponding page. 
def blogs(request):
    all_blogs = Blog.objects.all()
    # Real-world view functions are almost always more complex than what you see here, and they can pass as much information as needed to render().
    context = {"blogs": all_blogs}
    # When we used the render() function to generate the home page, all the information it needed was already in the template files.
    return render(request, "blogs/blogs.html", context)

@login_required
def meus_blogs(request):
    meus_blogs = Blog.objects.filter(owner=request.user)
    # Real-world view functions are almost always more complex than what you see here, and they can pass as much information as needed to render().
    context = {"blogs": meus_blogs}
    # When we used the render() function to generate the home page, all the information it needed was already in the template files.
    return render(request, "blogs/blogs.html", context)
def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.all()
    
    context = {
        "blog": blog,
        "posts": posts,
    }
    return render(request, "blogs/blog.html", context)

def post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    blog = post.blog

    context = {
        "post": post,
        "blog": blog,
    }
    return render(request, "blogs/post.html", context)

@login_required
def new_blog(request):
    if request.method != "POST":
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return redirect("blogs:blogs")

    context = {"form": form}
    return render(request, "blogs/new_blog.html", context)

@login_required
def new_post(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    
    # Only allow blog owners to add new posts.
    if request.user != blog.owner:
        return redirect("blogs:index")
    
    if request.method != "POST":
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.blog = blog
            new_post.save()
            return redirect("blogs:blog", blog_id)

    context = {"form": form, "blog": blog}
    return render(request, "blogs/new_post.html", context)

blogs/templates/blogs/base.html
{% load static %}

<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'chota.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'custom.css' %}" rel="stylesheet" type="text/css">
    <title>BlogMaker Lite</title>
  </head>
  <body>

    <nav class="nav">
      <div class="nav-left">
        <a class="active" href="{% url 'blogs:index' %}">BlogMaker Lite</a>
        <a href="{% url 'blogs:blogs' %}">Todos os Blogs</a>

        {% if user.is_authenticated %}
          <a href="{% url 'blogs:new_blog' %}">Novo blog</a>
          <a href="{% url 'blogs:meus_blogs' %}">Meus blogs</a>
        {% endif %}        
      </div>

      <div class="nav-right">
        {% if user.is_authenticated %}
          <span class="is-vertical-align">Olá, {{ user.username }}.</span>
          <form action="{% url 'accounts:logout' %}" method="post" class="is-vertical-align">
          {% csrf_token %}
            <button class="button outline">Sair</button>
          </form>        
        {% else %}
          <a href="{% url 'accounts:login' %}">Acessar</a>
          <a href="{% url 'accounts:register' %}">Registrar</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
      {% block content %}{% endblock content %}
    </div>

  </body>
</html>

blogs/templates/blogs/blog.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>{{ blog.title }}</h2>
  <p class="text-right blog-owner">{{ blog.owner.username }}</p>

  {% for post in posts %}

    <div class="card">
      <header>
        <h3><a href="{% url 'blogs:post' post.id %}">
            {{ post.title }}</a></h3>
      </header>
      <p>{{ post.date_added|date:"DATE_FORMAT"}}</p>
      <p>{{ post.body|truncatewords:10 }}</p>
    </div>
    
  {% empty %}
    <h3>Nenhum artigo foi postado ainda para este blog.</h3>
  {% endfor %}

  {% if request.user == blog.owner %}
  <a class="button primary"
    href="{% url 'blogs:new_post' blog.id %}">Nova postagem</a>
  {% endif %}

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}

{% block content %}
  
  <h2>Blogs</h2>

  {% for blog in blogs %}
    <div class="card">
      <header>
        <h3>
          <a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>
        </h3>
      </header>
      <p>{{ blog.description }}</p>
      <p class="text-right">{{ blog.owner.username }}</p>
    </div>
  {% empty %}
    <h3>Nenhum blog foi adicionado ainda.</h3>
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}

    <div class="hero">
        <p><span class="title">BlogMaker Lite</span> permite você compartilhar seus textos com o mundo.</p>
        <p>Cria um blog hoje, e escreva o que você está pensando!</p>
    </div>

    <a class="button primary" href="{% url 'blogs:blogs' %}">Todos os blogs</a>

{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>Crie um novo blog</h2>

  <form action="{% url 'blogs:new_blog' %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}

    <button name="submit" class="button primary">Criar blog</button>
  </form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>{{ blog.title }}</h2>
  <h3>Write a new post:</h3>

  <form action="{% url 'blogs:new_post' blog.id %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button class="button primary" name="submit">Salvar postagem</button>
  </form>

{% endblock content %}

blogs/templates/blogs/post.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>{{ post.title }}</h2>
  <p class="text-right blog-owner">{{ blog.owner.username }}</p>
  
  <div class="text-right">
    <span>{{ post.date_added|date:"DATE_FORMAT"}}</span> |
    <span>
        <a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>
    </span>
  </div>

  <div class="post-body">
    {{ post.body|linebreaks }}
  </div>

{% endblock content %}

templates/blogs.html
{% extends "base.html" %}

{% block content %}
  
  <h2>Blogs</h2>

  {% for blog in blogs %}
    <div class="card">
      <header><h3>{{ blog.title }}</h3></header>
      <p>{{ blog.description }}</p>
    </div>
  {% empty %}
    <h3>Nenhum blog foi adicionado ainda.</h3>
  {% endfor %}

{% endblock content %}

templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="hero">
        <p><span class="title">BlogMaker Lite</span> permite você compartilhar seus textos com o mundo.</p>
        <p>Cria um blog hoje, e escreva o que você está pensando!</p>
    </div>

    <a class="button primary" href="{% url 'blogs' %}">Todos os blogs</a>

{% endblock content %}